### ISSUE TITLE
[EXOTIC CASE]DSPManager Crash :(

### ISSUE THREAD

**Issue by ikillcypher2** [james34602/JamesDSPManager#6] opened 2017-05-27 09:58 UTC
Hi

I'm using your dspmanager on my ROM lineageos 14.1 stock no kernel modification on my oneplus 3t but it seems like the application crash I did what the readme said 

Logs attached

https://ibb.co/dbfqdF
https://ibb.co/kCqCsa

Android : Lineageos 14.1 NIGHTLY 25052017
Kernel : Stock

Deleted : AudioFX 

Possible if you can make a twrp zip in the future it helps

**Comment by james34602** [comment] 2017-05-28 04:44
May fixed on next update

**Comment by james34602** [comment] 2017-05-28 13:13
I have test on Note 2, Note 4, S5, OnePlus 3T, Android-x86(Core M, Core i7), no obvious error.
Below is error re-produced by missing libjamesdsp.so and audio_effects.conf.
OnePlus 3T come with audio_effects.conf in /system/vendor/etc/ default, you can override it with my .conf or add required uuid if you know how to.
--------- beginning of crash
05-28 21:07:01.541  3574  3574 E AndroidRuntime: FATAL EXCEPTION: main
05-28 21:07:01.541  3574  3574 E AndroidRuntime: Process: james.dsp, PID: 3574
05-28 21:07:01.541  3574  3574 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.action.OPEN_AUDIO_EFFECT_CONTROL_SESSION flg=0x10 (has extras) } in james.dsp.service.HeadsetService$1@c530d00
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at james.dsp.service.HeadsetService$JDSPModule.<init>(HeadsetService.java:69)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at james.dsp.service.HeadsetService$JDSPModule.<init>(HeadsetService.java:55)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at james.dsp.service.HeadsetService$1.onReceive(HeadsetService.java:263)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	... 7 more
05-28 21:07:01.541  3574  3574 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at james.dsp.service.HeadsetService$JDSPModule.<init>(HeadsetService.java:64)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	... 10 more
05-28 21:07:01.541  3574  3574 E AndroidRuntime: Caused by: java.lang.RuntimeException: Cannot initialize effect engine for type: ec7178ec-e5e1-4432-a3f4-4657e6795210 Error: -3
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:411)
05-28 21:07:01.541  3574  3574 E AndroidRuntime: 	... 13 more
05-28 21:07:01.588  1356  5257 I Adreno  : QUALCOMM build                   : 853a1ff, I9c435c2712
05-28 21:07:01.588  1356  5257 I Adreno  : Build Date                       : 01/10/17

**Comment by ikillcypher** [comment] 2017-05-29 08:15
Hi possible if you make a recovery installer ? Cause it seems like I did what you told me but it fail or possible recommend me a good file manager that is able to do that without much hassle thanks :)

**Comment by james34602** [comment] 2017-05-29 10:55
Use Root Explorer / CM file manager, set file permission for rw-r-r will possibly work on most device

**Comment by ikillcypher2** [comment] 2017-05-29 11:47
tested with the given permission to the lib file and copy to soundfx with permission for rw-r-r and still same issue application crashed any other solution ?

**Comment by ikillcypher2** [comment] 2017-05-29 11:57
Attached Logs : http://imgur.com/a/trVkT

**Comment by james34602** [comment] 2017-05-30 00:35
I don't know why it doesn't works, my OnePlus 3T work fine, [https://github.com/james34602/JamesDSPManager/blob/master/Screenshot_20170530-082307.png](url)
Some may the causes:
1. Other effect override .conf file with jdsp UUID removed
2. apk is not installed directly(very unlikely)

**Comment by ikillcypher2** [comment] 2017-05-30 01:55
I did exactly what you said, possible if you make a recovery installer from twrp to do the following remove LineageOS stock Equalizer, drop so on soundfx and vendor with it setted permission, install APK I think this process should be universal to all the devices. :( if that does not work then something is seriously wrong. 

tbh I did what you asked for, same issues.

**Comment by james34602** [comment] 2017-05-30 03:30
May be I upload cwm version tonight, it will have arm and x86 version.

Note: I don't guarantee some system "improvement" will work fine with this application. deep buffer etc.

**Comment by therealahrion** [comment] 2017-05-30 03:31
It's because he used x64. I have a OP3 and used x64 version and it didn't
work. When I used the regular version it worked. I can confirm my deep
buffer hacks work.

**Comment by ikillcypher2** [comment] 2017-05-30 06:39
oneplus3/3t is Arm64 o.o so why only upload x86 and arm version anyway make it universal for all phones.

**Comment by james34602** [comment] 2017-05-30 08:21
Surely x86 version is not for OnePlus.
libjamesDSPImpulseToolbox.so need to work because of it is native code, it is used in convolver provide WAV and more format reading functions.
Most phone are ARM powered, don't need to worry about that, install ARM version should ok.

**Comment by ikillcypher2** [comment] 2017-05-30 08:56
alright I will be waiting for the ARM Version, be sure to check and remove any existing files that may causes some issues, also be sure it remove the default equalizer that came with LineageOS :) looking forward for the flashable zip :)

**Comment by james34602** [comment] 2017-05-30 14:42
New update released!
Update log from my OnePlus3T: [https://github.com/james34602/JamesDSPManager/blob/master/Misc/recovery.log](Recovery log)
What I did is:
1. Install main LineageOS nightly build
2. Install Google Play (Optional)
3. Root (Optional)
4. Install JamesDSPManager

**Comment by james34602** [comment] 2017-05-30 14:56
> It's because he used x64. I have a OP3 and used x64 version and it didn't
work. When I used the regular version it worked. I can confirm my deep
buffer hacks work.

I'm pretty sure it will go wrong if put shared library in lib64, there have atleast two reason:
1. System may not run a regular 32 bit binary by forced 64 bit call, unless you compile it yourself.
2. Many 64 bit devices don't actually use many 64 bit library...I know it is a shame, but you can test it, my test show that removing /system/lib64/soundfx stuffs won't make any crash, that mean they are not running

**Comment by ikillcypher2** [comment] 2017-05-31 02:06
it does not work :( still crashes is it because I removed the default AudioFX o.o from LineageOS ?

**Comment by james34602** [comment] 2017-05-31 02:52
If install zip under un-touched /system partition, then it will work, then sorry no luck. I think you got a buggy OnePlus 3T

**Comment by ikillcypher2** [comment] 2017-05-31 11:21
I will update to new nightly and try to reflash again, see if it works, I flash viper4android without any issues o.o

**Comment by james34602** [comment] 2017-05-31 13:21
Viper4Android + JamesDSP together may cause crash, if this is not the cause, then give up, because many devices just work fine with just plain file copy.

**Comment by james34602** [comment] 2017-05-31 15:36
[https://github.com/james34602/JamesDSPManager/releases/tag/31May2017](url)
Add UUID identification see if it works...

**Comment by ikillcypher2** [comment] 2017-06-04 01:16
the 31 May 2017 fixed the issue, the UUID did the trick.

finally omg thanks :)

**Comment by james34602** [comment] 2017-06-04 01:53
This time I use custom UUID, this could be a feature rollback.
CM DSP: Custom UUID, NULL UUID
JamesDSP: Custom UUID, CUSTOM UUID.
You could test one more version of JamesDSP, since I will upload it tonight, including source codr commits.

**Comment by therealahrion** [comment] 2017-06-04 01:54
Wouldn't it be better because it wouldn't interfere with other effect uuids
like v4a?

**Comment by james34602** [comment] 2017-06-04 01:55
I don't know, this need further study

**Comment by ikillcypher2** [comment] 2017-06-04 06:06
yeah it is better anyway I notice this does not work on soundcloud,spoify and other online streaming application known feature

**Comment by james34602** [comment] 2017-06-04 13:29
Try my new one, let's see if it work.

**Closed** 2017-06-06 23:59 UTC

**Comment by ikillcypher2** [comment] 2017-06-10 03:18
Tested and it works fine, flashed the 5 June Version :+1:
